artifacts:
  ARTIFACTS_DIR: artifacts
  TRAINED_MODEL_DIR: model
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: VGG16_base_model.h5
  UPDATED_BASE_MODEL_NAME: updated_VGG_base_model.h5
  CHECKPOINTS_DIR: checkpoints
  BASE_LOG_DIR: base_model_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
  CALLBACKS_DIR: callbacks
  DATA_DIR: data
  

source_download_dirs:
   - ../MIT_Images/airport_inside
   - ../MIT_Images/artstudio
   - ../MIT_Images/auditorium
   - ../MIT_Images/bakery
   - ../MIT_Images/bar
   - ../MIT_Images/bathroom
   - ../MIT_Images/bedroom
   - ../MIT_Images/bookstore
   - ../MIT_Images/bowling
   - ../MIT_Images/buffet
   - ../MIT_Images/casino
   - ../MIT_Images/children_room
   - ../MIT_Images/church_inside
   - ../MIT_Images/classroom
   - ../MIT_Images/cloister
   - ../MIT_Images/closet
   - ../MIT_Images/clothingstore
   - ../MIT_Images/computerroom
   - ../MIT_Images/concert_hall
   - ../MIT_Images/corridor
   - ../MIT_Images/deli
   - ../MIT_Images/dentaloffice
   - ../MIT_Images/dining_room
   - ../MIT_Images/elevator
   - ../MIT_Images/fastfood_restaurant
   - ../MIT_Images/florist
   - ../MIT_Images/gameroom
   - ../MIT_Images/garage
   - ../MIT_Images/greenhouse
   - ../MIT_Images/grocerystore
   - ../MIT_Images/gym
   - ../MIT_Images/hairsalon
   - ../MIT_Images/hospitalroom
   - ../MIT_Images/inside_bus
   - ../MIT_Images/inside_subway
   - ../MIT_Images/jewelleryshop
   - ../MIT_Images/kindergarden
   - ../MIT_Images/kitchen
   - ../MIT_Images/laboratorywet
   - ../MIT_Images/laundromat
   - ../MIT_Images/library
   - ../MIT_Images/livingroom
   - ../MIT_Images/lobby
   - ../MIT_Images/locker_room
   - ../MIT_Images/mall
   - ../MIT_Images/meeting_room
   - ../MIT_Images/movietheater
   - ../MIT_Images/museum
   - ../MIT_Images/nursery
   - ../MIT_Images/office
   - ../MIT_Images/operating_room
   - ../MIT_Images/pantry
   - ../MIT_Images/poolinside
   - ../MIT_Images/prisoncell
   - ../MIT_Images/restaurant
   - ../MIT_Images/restaurant_kitchen
   - ../MIT_Images/shoeshop
   - ../MIT_Images/stairscase
   - ../MIT_Images/studiomusic
   - ../MIT_Images/subway
   - ../MIT_Images/toystore
   - ../MIT_Images/trainstation
   - ../MIT_Images/tv_studio
   - ../MIT_Images/videostore
   - ../MIT_Images/waitingroom
   - ../MIT_Images/warehouse
   - ../MIT_Images/winecellar

local_data_dirs:
   -  data/airport_inside
   -  data/artstudio
   -  data/auditorium
   -  data/bakery
   -  data/bar
   -  data/bathroom
   -  data/bedroom
   -  data/bookstore
   -  data/bowling
   -  data/buffet
   -  data/casino
   -  data/children_room
   -  data/church_inside
   -  data/classroom
   -  data/cloister
   -  data/closet
   -  data/clothingstore
   -  data/computerroom
   -  data/concert_hall
   -  data/corridor
   -  data/deli
   -  data/dentaloffice
   -  data/dining_room
   -  data/elevator
   -  data/fastfood_resta
   -  data/florist
   -  data/gameroom
   -  data/garage
   -  data/greenhouse
   -  data/grocerystore
   -  data/gym
   -  data/hairsalon
   -  data/hospitalroom
   -  data/inside_bus
   -  data/inside_subway
   -  data/jewelleryshop
   -  data/kindergarden
   -  data/kitchen
   -  data/laboratorywet
   -  data/laundromat
   -  data/library
   -  data/livingroom
   -  data/lobby
   -  data/locker_room
   -  data/mall
   -  data/meeting_room
   -  data/movietheater
   -  data/museum
   -  data/nursery
   -  data/office
   -  data/operating_room
   -  data/pantry
   -  data/poolinside
   -  data/prisoncell
   -  data/restaurant
   -  data/restaurant_kit
   -  data/shoeshop
   -  data/stairscase
   -  data/studiomusic
   -  data/subway
   -  data/toystore
   -  data/trainstation
   -  data/tv_studio
   -  data/videostore
   -  data/waitingroom
   -  data/warehouse
   -  data/winecellar